version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: todosdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    image: todo-app
    command: python ./main.py
    volumes:
      - .:/app
    ports:
      - "5001:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/todosdb

  init-db:
    build: .
    command: python ./src/db/init_db.py
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/todosdb


volumes:
  postgres_data:
