apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      initContainers:
        - name: init-db
          image: icradber/todo-app:latest
          command: [ 'python', './src/db/init_db.py' ]
          env:
            - name: DATABASE_URL
              value: "postgresql://user:password@postgres:5432/todosdb"
      containers:
      - name: todo-app
        image: icradber/todo-app:latest
        command: ["python", "./main.py"]
        ports:
        - containerPort: 3000
        env:
          - name: DATABASE_URL
            value: "postgresql://user:password@postgres:5432/todosdb"
      volumes:
      - name: app-volume
        persistentVolumeClaim:
          claimName: app-pvc
